### ISSUE TITLE
Can alpha-zero learn Bejeweled? 

### ISSUE THREAD

**Issue by tensorgpu** [suragnair/alpha-zero-general#100]
For Bejeweled, after the same colour in a row disappeared, the jewel from row above will move down and if the new row match then they will dissappear too. One action will cause other several moves.

Assuming no new jewel will be generated, just find the best move to solve all the existing jewels.

Can alpha-zero solve this scenario?

**Comment by JernejHabjan** [comment]
Hi @tensorgpu 

Yes it can, you just have to implement custom game logic.
You would have two smaller problems:
1. pieces would have to be encoded numerically or one-hot style, because you have number of different piece types (by color i presume).This needs to be done because you dont have +1 and -1 pieces (black and white).
2. synthetic endgame condition would have to be implemented if player is playing game for too long(N iterations) after which winner should be decided by which player generated higher score.

**Comment by tensorgpu** [comment]
Thank you Jernej Habjan, I will try, you contributed a lot to this forum.

**Comment by JernejHabjan** [comment]
@tensorgpu For help you can look at my implementation of [RTS game](https://github.com/JernejHabjan/alpha-zero-general) with alpha zero, which has both of your problems.
Have fun

**Comment by tensorgpu** [comment]
@JernejHabjan Thank you! A feature rich example!
