### ISSUE TITLE
Possible bug in Coach.py?

### ISSUE THREAD

**Issue by zhyack** [suragnair/alpha-zero-general#103]
At line 114 in Coach.py, we get `self.pnet.load_checkpoint(folder=self.args.checkpoint, filename='temp.pth.tar')`, which happens just after `self.nnet.save_checkpoint(folder=self.args.checkpoint, filename='temp.pth.tar')`. And then it starts training `nnet`, and then PITTING process between `pnet` and `nnet`.

My concern is: I think we should use the current best model for `pnet`, but not the old version of `nnet`, for the last version of `nnet` may be rejected before (not the current best model).

Therefore, should line 114 be `self.pnet.load_checkpoint(folder=self.args.checkpoint, filename='best.pth.tar')` ?
BTW, if we modify line 114 like mentioned above, we may also need to further refine it by
```
if os.path.exists(os.path.join(self.args.checkpoint,'best.pth.tar.index')):
    self.pnet.load_checkpoint(folder=self.args.checkpoint, filename='best.pth.tar')
else:
    self.pnet.save_checkpoint(folder=self.args.checkpoint, filename='best.pth.tar')
```

**Comment by djdookie** [comment]
No I think its correct.
The idea seems to be:
pnet (temp.pth.tar) is the previous network before training, nnet is the trained network after training.
Both are pitting against each other.
If nnet beats its untrained version, it is accepted and saved as best.pth.tar.
If nnet doesn't beat its untrained version, it's rejected and falls back to temp.pth.tar (untrained version).

Important fact: **before training, pnet == nnet == temp.pth.tar == best.pth.tar**,
as long as we found a better net once. otherwise best.pth.tar doesn't exist and temp.pth.tar is only the initial random network.
