### ISSUE TITLE
GetActionSize +1?

### ISSUE THREAD

**Issue by GenuineGuineapig** [suragnair/alpha-zero-general#138]
Hi,
I am currently working with a friend on our own adaptation of a game and everything went smoothly. However, when we decided to train, the program crashed due to Pis Array length being 801 instead of 800 (our gamesize is 10^2 *8). When we had a look at the other already implemented games, we noted that tafl is the only game where not a +1 is added. 

Is it possible for you to explain a little the background of this +1 and maybe if it's (and if so, where) hardcoded somewhere?

**Comment by suragnair** [comment]
Hi, the +1 is usually added to games that allow a “SKIP” action such that no change is made to the board. In othello, the plus 1 is added here: https://github.com/suragnair/alpha-zero-general/blob/8fea86449d78434456ad7d1f585dd0f945afc109/othello/OthelloGame.py#L24

And the special casing for handling such moves is here: https://github.com/suragnair/alpha-zero-general/blob/8fea86449d78434456ad7d1f585dd0f945afc109/othello/OthelloGame.py#L29

If your game does not permit skipping, then you should not include the +1.

**Comment by moritzmoritz98** [comment]
Thanks for your reply, @suragnair!
We tried exactly this too and as @GenuineGuineapig already mentioned is our problem right know, that although we removed the +1 in our board game adaptation, the model still fails to learn (prediction is fine tho) due to the proposed size mismatch: the neural network provides our reduced `actionsize`  of 800, whereas for some reason the length of pi (the one from the training examples) stays the same with `actionsize +1` / 801.

Unfortunately, we can't share the code, however, do you've got some thoughts on that?
Thanks a lot!

**Comment by moritzmoritz98** [comment]
Okay, I finally solved the bug: Changing the action size is not enough since you have to take into account that the `getSymmetries` method is based on the "SKIP" action as well... :man_facepalming: 
https://github.com/suragnair/alpha-zero-general/blob/8fea86449d78434456ad7d1f585dd0f945afc109/othello/OthelloGame.py#L80

**Comment by gms2009** [comment]
on othello 8x8, +1 may not be enough

(;GM[2]
FF[4]
CA[UTF-8]
AP[Quarry:0.2.0]
SZ[8]
PB[player1]
PW[player2]
RE[Void]
;B[dc] ;W[cc] ;B[bc] ;W[ce] ;B[ff] ;W[db] ;B[cb] ;W[bd] ;B[eb] ;W[ec] ;B[cd] ;W[fd] ;B[gc] ;W[fa] ;B[fc] ;W[gd] ;B[fe] ;W[hc] ;B[ae] ;W[fg] ;B[df] ;W[ad] ;B[ge] ;W[eg] ;B[cg] ;W[ea] ;B[fh] ;W[ac] ;B[ab] ;W[gf] ;B[bf] ;W[dg] ;B[ef] ;W[bh] ;B[cf] ;W[eh] ;B[ch] ;W[dh] ;B[ah] ;W[af] ;B[ag] ;W[gg] ;B[be] ;W[bg] ;B[hg] ;W[gh] ;B[hh] ;W[ca] ;B[hf] ;W[he] ;B[bb] ;W[] ;B[hd] ;W[] ;B[hb] ;W[gb] ;B[fb] ;W[da] ;B[] ;W[ba] ;B[] ;W[ha] ;B[ga] ;W[] ;B[aa]
)

**Comment by gms2009** [comment]
one othello 8x8, lot of games with more than 1 skip
but seems the program runs ok with  +1 code 

(;GM[2]
FF[4]
CA[UTF-8]
AP[Quarry:0.2.0]
SZ[8]
PB[player1]
PW[player2]
RE[Void]
;B[dc] ;W[cc] ;B[bc] ;W[ce] ;B[ff] ;W[db] ;B[cb] ;W[bd] ;B[eb] ;W[ec] ;B[cd] ;W[fd] ;B[gc] ;W[fa] ;B[fc] ;W[gd] ;B[fe] ;W[hc] ;B[ae] ;W[fg] ;B[df] ;W[ad] ;B[ge] ;W[eg] ;B[cg] ;W[ea] ;B[fh] ;W[ac] ;B[ab] ;W[gf] ;B[bf] ;W[dg] ;B[ef] ;W[bh] ;B[cf] ;W[eh] ;B[ch] ;W[dh] ;B[ah] ;W[af] ;B[ag] ;W[gg] ;B[be] ;W[bg] ;B[hg] ;W[gh] ;B[hh] ;W[ca] ;B[hf] ;W[he] ;B[bb] ;W[] ;B[hd] ;W[] ;B[hb] ;W[gb] ;B[fb] ;W[da] ;B[] ;W[ba] ;B[] ;W[ha] ;B[ga] ;W[] ;B[aa]
)
