### ISSUE TITLE
parameters for 8x8 othello

### ISSUE THREAD

**Issue by gms2009** [suragnair/alpha-zero-general#141]
Any suggested parameter for 8x8 othello?  9 out of 10 got rejected is not a good way to train.

**Comment by suragnair** [comment]
As high a number of MCTS simulations as possible would be good.

**Comment by aletote** [comment]
> 9 out of 10 got rejected is not a good way to train.

What do you mean by that?

**Comment by aletote** [comment]
> As high a number of MCTS simulations as possible would be good. I personally didn't have much success training 8x8 othello either.

Care to expand a bit? What happened?

**Comment by gms2009** [comment]
on Coach.py  when new model play against old one, if win percentage does not reach 60%, got rejected
            if pwins+nwins == 0 or float(nwins)/(pwins+nwins) < self.args.updateThreshold:
                print('REJECTING NEW MODEL')
                self.nnet.load_checkpoint(folder=self.args.checkpoint, filename='temp.pth.tar')
            else:
                print('ACCEPTING NEW MODEL')
                self.nnet.save_checkpoint(folder=self.args.checkpoint, filename=

**Comment by aletote** [comment]
Interesting, so basically the new model is not confident enough or doesn't win enough times for it to be accepted. Do you have any ideas why that would be the case?

**Comment by MerceaOtniel** [comment]
Hello. You can actually train Othello 8x8 to a pretty good level in a reasonable time without rejecting the model that much. I managed to train an Othello 8x8 in 3-4 days on a single GPU to the level of some of the programs that you can play against on the internet. I have a repository which is an improved version over this in many ways, so i don't know exactly if the problem is in the code or in the way you set your parameters. Be also aware that in this repository, a draw in Othello is not handled as a draw but as a lose, and i assure you that there are many draws when training AlphaZero (i spent a lot of time playing and improving this project and i saw it numerous times). If you wish, you can look on my Git for my version of this project. One of the reasons why your model is not training very well would be the value of your parameters. For example i used something like this when training: 
    'numIters': 75,
    'numEps': 200,
    'updateThreshold': 0.55,
    'numMCTSSims': 200,

**Comment by suragnair** [comment]
@MerceaOtniel that’s great to know. Would it be possible to submit the model into the pretrained_models folder? I’m sure a lot of people could use it as a starting point for further training.

**Comment by MerceaOtniel** [comment]
Should i open a pull request?

**Comment by suragnair** [comment]
That would be great!

**Comment by MerceaOtniel** [comment]
I get " is 159.25 MB; this exceeds GitHub's file size limit of 100.00 MB". How we can solve it?

**Comment by suragnair** [comment]
Oh. Can you upload it perhaps on Zenodo and share the link?

**Comment by MerceaOtniel** [comment]
I will upload the weights...but your architecture for Othello is a bit different to mine, so maybe there will be problems when loading the weights in your architecture

**Comment by suragnair** [comment]
I see, no worries then! Thanks.
