### ISSUE TITLE
Faster way to find best_action?

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#188]
There was a question on the Disqus regarding finding the `best_action`; I'd like to surface it here to get more attention:

```python
args1 = dotdict({'numMCTSSims': 50, 'cpuct':1.0})
mcts1 = MCTS(game, net, args1)
best_action = np.argmax(mcts1.getActionProb(current_board, temp=0))
```
Why can't we just simply do:

```python
p, v = net.predict(current_board)
best_action = np.argmax(p)
```

**Comment by jrbuhl93** [comment]
Your code gets the maximum from the raw probability output predicted by the neural net without going through and monte carlo tree search. In the paper (https://discovery.ucl.ac.uk/id/eprint/10045895/1/agz_unformatted_nature.pdf) they describe the elo of an agent that made moves this way in Go:

`Figure 6b shows the performance of each program on an Elo scale. The raw neural network,
without using any lookahead, achieved an Elo rating of 3,055. AlphaGo Zero achieved a rating
of 5,185, compared to 4,858 for AlphaGo Master, 3,739 for AlphaGo Lee and 3,144 for AlphaGo
Fan.`

**Comment by mikhail** [comment]
@jrbuhl93 Thanks for the reference -- that helps. Can you help me understand why this is the case? Is the approach without a lookahead worse because not all paths were explored? or is there some other reason?

I'm curious about this because I'm simulating physics and MCTS(50) can take a very long time. This is totally ok during training, but during playing vs a human is quite unpleasant

**Comment by jrbuhl93** [comment]
I think it will vary depending on the complexity of the domain for how much the MCTS improves the raw nnet policy. In Tic Tac Toe the raw policy will be enough, but in Go performing X simulations allows the network to also incorporate the policy and value the nnet outputs for future boards/environments when determining the current action.

There are likely solutions to the complexity of simulating environments with many time steps because deepmind was able to train an agent for starcraft 2 and openai for dota2. I am not yet familiar with these methods, but maybe I will know more in a couple months.

**Comment by mikhail** [comment]
Those are MuZero. In short - the training is to correlate current state with next action, unlike AlphaZero correlating the current state with next-wanted-state
