### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mshanak** [suragnair/alpha-zero-general#191]
I am trying to run this code on a customer game, The experiment works for some iterations but then but I keep getting  the following error:

```

Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 57, in main
    c.learn()
  File ".../alpha-zero-general-master/Coach.py", line 89, in learn
    iterationTrainExamples += self.executeEpisode()
  File "... /alpha-zero-general-master/Coach.py", line 58, in executeEpisode
    pi = self.mcts.getActionProb(canonicalBoard, temp=temp)
  File ".... /alpha-zero-general-master/MCTS.py", line 56, in getActionProb
    probs = [x / counts_sum for x in counts]
  File "...alpha-zero-general-master/MCTS.py", line 56, in <listcomp>
    probs = [x / counts_sum for x in counts]
ZeroDivisionError: float division by zero


```

The configuration arguments in `main.py` are as follow:

```

args = dotdict({
    'numIters': 1000,
    'numEps': 100,              # Number of complete self-play games to simulate during a new iteration.
    'tempThreshold': 15,        #
    'updateThreshold': 0.6,     # During arena playoff, the new neural net will be accepted if threshold or more of games are won.
    'maxlenOfQueue': 200000,    # Number of game examples to train the neural networks.
    'numMCTSSims': 50,          # Number of games moves for MCTS to simulate.
    'arenaCompare': 40,         # Number of games to play during arena play to determine if new net will be accepted.
    'cpuct': 1,

    'checkpoint': './temp/',
    'load_model': False,
    'load_folder_file': ('/dev/models/8x100x50','best.pth.tar'),
    'numItersForTrainExamplesHistory': 20,

})




```
Is there any solution or explanation for `counts_sum` zero value?

**Comment by jrbuhl93** [comment]
I would guess self.game.getActionSize() is retuning 0.

**Comment by mshanak** [comment]
> I would guess self.game.getActionSize() is returning 0.

I printed the `counts` variable when the `if counts_sum==0`, the result was a vector of zeros `[0,0,0..,0]`, this means that `self.game.getActionSize()` is returning the correct size.

I wonder why the following line returning an all-zero vector `[0,0,0..,0]`
```
        counts = [self.Number_visits_sa[(s, a)] if (s, a) in self.Number_visits_sa else 0 for a in range(self.game.getActionSize())]

```

**Comment by jrbuhl93** [comment]
That is unexpected since you have 'numMCTSSims': 50, so it should be performing 50 searches. Maybe you could put print statements where Nsa is incremented to make sure that is being called.

**Comment by goshawk22** [comment]
I am also having a similar problem. I am implementing a chess version and everything works when I pit two human players, or two random players, together, but the MCTS throws a Float Division by zero error.
I did some debugging and it seems that every value in counts is equal to zero. If `temp` = 0, the MCTS algorithm chooses randomly from counts
`bestAs = np.array(np.argwhere(counts == np.max(counts))).flatten()`
and, because not all of these moves are valid, the best action can be an illegal move and cause an error.
I'm not really sure where this problem is caused (there isn't an error when playing the game with two human players, and a win is correctly identified).

**Comment by goshawk22** [comment]
I worked out what was wrong with my implementation - don't know if it will help anyone else.
I wasn't copying the board before getting the next state which meant that whenever the MCTS algorithm explored an action, it would apply the action to the real board. A simple mistake!

**Comment by jamesbraza** [comment]
I am hitting this on the first invocation of `MCTS.getActionProb` with a [`chess.Board`](https://github.com/niklasf/python-chess/blob/v1.9.4/chess/__init__.py#L1450), where my `getNextState` could in-place mutate the board:

```none
    a b c d e f g h
  . --------------- .
8 | r n b q k b n r | 8
7 | p p p p p p p p | 7
6 | . . . . . . . . | 6
5 | . . . . . . . . | 5
4 | . . . . . . . . | 4
3 | . . . . . . . . | 3
2 | P P P P P P P P | 2
1 | R N B Q K B N R | 1
  * --------------- *
    a b c d e f g h
```

After a few `MCTS.search` calls [here in `MCTS.getActionProb`](https://github.com/suragnair/alpha-zero-general/blob/3334001afc70bfe29af5f944a21a611c9bb91bd3/MCTS.py#L38), you can see the effects:

```none
    a b c d e f g h
  . --------------- .
8 | r n b q k b . r | 8
7 | p p p p p p p p | 7
6 | . . . . . . . n | 6
5 | . . . . . . . . | 5
4 | . . . . . . . . | 4
3 | . . . . . . . N | 3
2 | P P P P P P P P | 2
1 | R N B Q K B . R | 1
  * --------------- *
    a b c d e f g h
```

Thank you @goshawk22 for figuring this out!  Imo it would be good to document in `Game.py` what methods are allowed to in-place mutate game state, and which are not.  I will open a PR for this in the coming weeks.

**Comment by jamesbraza** [comment]
Hello all, as I have a few other PRs (https://github.com/suragnair/alpha-zero-general/pull/299, https://github.com/suragnair/alpha-zero-general/pull/300) that went unreviewed here, I am going to not contribute a PR for this.

For those hitting this in the future, feel free to reference my `Game` implementation here: https://github.com/jamesbraza/cs234-dreamchess/blob/main/azg_chess/game.py
- `getValidMoves`, `getGameEnded`, `getSymmetries`, `stringRepresentation`: doesn't mutate or copy the passed in `board`
    - Think: read only
- `getNextState`: doesn't mutate the passed in `board`. Instead will (1) make a copy of the canonicalized `board`, and (2) possibly mutate that copy
    - Think: read only, but can copy to write
- `getCanonicalForm`: can mutate the passed in `board`, for an optimization (keep reading)
    - Think: can write

The placement of read only is important because `MCTS` does store board state. At the same time, having `getCanonicalForm` be able to intelligently mutate the board can speed all future `getCanonicalForm` calls without affecting the stored board inside `MCTS`.  Hopefully this helps someone, cheers!
