### ISSUE TITLE
Coach should load best model for self play?

### ISSUE THREAD

**Issue by goshawk22** [suragnair/alpha-zero-general#212]
In https://github.com/suragnair/alpha-zero-general/blob/5156c7fd1d2f3e5fefe732a4b2e0ffc5b272f819/Coach.py#L124 Coach loads the most recent model which is then used for selfplay. Am I right in thinking that here we should load the best model?
An example:
`self.nnet.load_checkpoint(folder=self.args.checkpoint, filename='best.pth.tar')`
This way self play is executed with the best model, as opposed to the mos recent model which was just rejected.

**Comment by peldszus** [comment]
The `temp` model is saved _before_ continuing training, and restored if the new model is rejected in the pit.

So, if I am not mistaken, it will be identical to the last `best` model.

Changing this so that `best` is restored might not change the results at all, but it might result in an error when starting fresh where no `best` yet exists.

**Comment by goshawk22** [comment]
Yes now I check again it makes sense!
