### ISSUE TITLE
Chess game implementation

### ISSUE THREAD

**Issue by JernejHabjan** [suragnair/alpha-zero-general#62]
Can this framework be used to implement games like chess or shogi?
If so, would then neural network have to receive multi dimensional input, because for example chess has different types of figures with different actions. This means that action space would look 3 dimensional, where the third dimension covers actions of figures?

Here for games like othello, gobang, tictactoe... neural network receives 2d input which is grid and actions for that grid correspond to places the next figure is placed on. But this cannot be applied directly to games like chess.

I'm trying to implement RTS game, which consists of grid for example 8x8, but each tile can host up to 5 figures, which have different number of actions like "walk up", "attack" etc..
My action size would be 
>grid_width * grid_height * 5 * num_actions

where num_actions is number of all actions for figures.

Can this type of game even be implemented in this algorithm?

**Comment by suragnair** [comment]
The code makes no assumptions about the state of the board except that it can be represented as a numpy array. You only need to ensure the dimension of your state and the input dimension of the neural network matches.

As for a 3D action space, you will ultimately have to flatten it and make it 1D to make it compatible with the code- this is not an issue since your neural network can model it as a 3D object (and use CNNs accordingly), and only flatten it in the end.

**Comment by JernejHabjan** [comment]
Thanks, I look forward to contributing to this repo with rts game.
I hope I'm not annoying with questions

**Comment by suragnair** [comment]
Of course not! :)
