### ISSUE TITLE
Mcts Simulations

### ISSUE THREAD

**Issue by JernejHabjan** [suragnair/alpha-zero-general#87]
Hi everybody

I have noticed that mcts tree leaf node gets action probability and value prediction from nnet.
```
self.Ps[s], v = self.nnet.predict(canonicalBoard)
```
It doesnt get actual state value by simulating game until end (player -1 or +1 won).
Rarely end game conditions with player winning are returned when executing mcts episode.

My question now is, why is mcts used in this algorithm? Its values are set very low (25-50) and not 1k-10k. Does this mean, that neural network gets updated only when single arena game condition is finished?

Why would increasing of mcts sims help while learning new model, because mcts never (rarely) even reaches end condition, to update nodes V value? It only gets V values retrieved from nnet and not from end game simulations, so predictions might be incorrect.

Would than be correct way to increase number of game iterations and episodes while learning instead of mcts sims?

**Comment by suragnair** [comment]
You are correct that MCTS doesn't get the actual state value by simulating until game end. But the reason MCTS helps intuitively is that it aggregates state values from its descendants- which are closer to the end game than the current state. The values are ~50 due to computational constraints, but DeepMind used ~1500 simulations. Even then, it doesn't guarantee seeing the end game conditions very often during a given search. But that's okay because you can imagine as training proceeds, the neural net learns accurate scores for states that are closer to the end game, and over training iterations, this knowledge is propagated up the tree to the earlier stages of the game. 

Does that make sense? I can go into more detail but I believe there definitely is value in increasing the number of MCTS simulations.

**Comment by JernejHabjan** [comment]
Ok, this makes sense.
I was just a bit confused, because i couldn't use raw MCTS with high simulation count, which would play game on its own without nnet, to check that end game evaluation function is working correctly.
Thanks for answering.
